plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-licenses.cjs
    spec: "https://raw.githubusercontent.com/mhassan1/yarn-plugin-licenses/v0.12.0/bundles/@yarnpkg/plugin-licenses.js"

yarnPath: .yarn/releases/yarn-3.6.3.cjs
